const loginScreen=document.getElementById('loginScreen'),registerScreen=document.getElementById('registerScreen'),generatorScreen=document.getElementById('generatorScreen'),loginForm=document.getElementById('loginForm'),registerForm=document.getElementById('registerForm'),showRegisterLink=document.getElementById('showRegister'),showLoginLink=document.getElementById('showLogin'),logoutBtn=document.getElementById('logoutBtn'),userNameDisplay=document.getElementById('userNameDisplay'),userEmailDisplay=document.getElementById('userEmailDisplay'),userInitial=document.getElementById('userInitial'),loginEmail=document.getElementById('loginEmail'),loginPassword=document.getElementById('loginPassword'),registerName=document.getElementById('registerName'),registerEmail=document.getElementById('registerEmail'),registerPassword=document.getElementById('registerPassword'),registerConfirmPassword=document.getElementById('registerConfirmPassword'),registerPasswordStrength=document.getElementById('registerPasswordStrength'),passwordOutput=document.getElementById('passwordOutput'),lengthSlider=document.getElementById('lengthSlider'),lengthValue=document.getElementById('lengthValue'),uppercaseCheck=document.getElementById('uppercase'),lowercaseCheck=document.getElementById('lowercase'),numbersCheck=document.getElementById('numbers'),symbolsCheck=document.getElementById('symbols'),excludeSimilarCheck=document.getElementById('excludeSimilar'),generateBtn=document.getElementById('generateBtn'),refreshBtn=document.getElementById('refreshBtn'),copyBtn=document.getElementById('copyBtn'),strengthFill=document.getElementById('strengthFill'),strengthText=document.getElementById('strengthText'),notification=document.getElementById('notification'),entropyValue=document.getElementById('entropyValue'),crackTime=document.getElementById('crackTime'),combinations=document.getElementById('combinations'),historyList=document.getElementById('historyList'),analysisContent=document.getElementById('analysisContent'),generateMultipleCheck=document.getElementById('generateMultiple'),multipleCountContainer=document.getElementById('multipleCountContainer'),multipleCountInput=document.getElementById('multipleCount'),clearHistoryBtn=document.getElementById('clearHistory'),normalModeBtn=document.getElementById('normalMode'),memorableModeBtn=document.getElementById('memorableMode'),pinModeBtn=document.getElementById('pinMode'),exportTxtBtn=document.getElementById('exportTxt'),exportJsonBtn=document.getElementById('exportJson'),exportCsvBtn=document.getElementById('exportCsv'),importBtn=document.getElementById('importBtn'),importFileInput=document.getElementById('importFile'),tabButtons=document.querySelectorAll('.tab-btn'),tabContents=document.querySelectorAll('.tab-content'),togglePasswordButtons=document.querySelectorAll('.toggle-password');
const uppercase='ABCDEFGHIJKLMNOPQRSTUVWXYZ',lowercase='abcdefghijklmnopqrstuvwxyz',numbers='0123456789',symbols='!@#$%^&*()_+-=[]{}|;:,.<>?',similarChars='0O1lI';
const memorableWords=['gato','cachorro','casa','carro','sol','lua','estrela','oceano','montanha','floresta','rio','cidade','livro','musica','arte','amor','felicidade','liberdade','esperanca','coragem','sabedoria','paz','forca','energia','vida','natureza','aventura','descoberta','criatividade','sonho'];
let currentUser=null,users=JSON.parse(localStorage.getItem('users'))||{},currentMode='normal',passwordHistory=[];
function checkAuth(){const session=JSON.parse(localStorage.getItem('currentSession'));if(session&&session.email&&users[session.email]){currentUser={email:session.email,name:users[session.email].name};showGenerator();return true}showLogin();return false}
function showLogin(){loginScreen.style.display='flex';registerScreen.style.display='none';generatorScreen.style.display='none';currentUser=null}
function showRegister(){loginScreen.style.display='none';registerScreen.style.display='flex';generatorScreen.style.display='none'}
function showGenerator(){loginScreen.style.display='none';registerScreen.style.display='none';generatorScreen.style.display='flex';if(currentUser){userNameDisplay.textContent=currentUser.name;userEmailDisplay.textContent=currentUser.email;userInitial.textContent=currentUser.name.charAt(0).toUpperCase();loadUserHistory()}}
function registerUser(name,email,password){if(users[email])return{success:false,message:'Este email já está cadastrado!'};const hashedPassword=btoa(password);users[email]={name,email,password:hashedPassword,createdAt:new Date().toISOString()};localStorage.setItem('users',JSON.stringify(users));return{success:true}}
function loginUser(email,password){const user=users[email];if(!user)return{success:false,message:'Email ou senha incorretos!'};const hashedPassword=btoa(password);if(user.password!==hashedPassword)return{success:false,message:'Email ou senha incorretos!'};currentUser={email,name:user.name};localStorage.setItem('currentSession',JSON.stringify({email,loginTime:new Date().toISOString()}));return{success:true}}
function logout(){currentUser=null;localStorage.removeItem('currentSession');showLogin();showNotification('Logout realizado com sucesso!','success')}
function getUserHistoryKey(){return currentUser?`passwordHistory_${currentUser.email}`:'passwordHistory'}
function getPasswordHistory(){return JSON.parse(localStorage.getItem(getUserHistoryKey()))||[]}
function savePasswordHistory(history){localStorage.setItem(getUserHistoryKey(),JSON.stringify(history))}
function loadUserHistory(){passwordHistory=getPasswordHistory();updateHistoryDisplay()}
showRegisterLink.addEventListener('click',e=>{e.preventDefault();showRegister()});
showLoginLink.addEventListener('click',e=>{e.preventDefault();showLogin()});
logoutBtn.addEventListener('click',logout);
loginForm.addEventListener('submit',e=>{e.preventDefault();const email=loginEmail.value.trim(),password=loginPassword.value;if(!email||!password){showNotification('Preencha todos os campos!','warning');return}const result=loginUser(email,password);if(result.success){showNotification(`Bem-vindo, ${currentUser.name}!`,'success');showGenerator();loginForm.reset()}else showNotification(result.message,'error')});
registerForm.addEventListener('submit',e=>{e.preventDefault();const name=registerName.value.trim(),email=registerEmail.value.trim(),password=registerPassword.value,confirmPassword=registerConfirmPassword.value;if(!name||!email||!password||!confirmPassword){showNotification('Preencha todos os campos!','warning');return}if(password.length<6){showNotification('A senha deve ter no mínimo 6 caracteres!','warning');return}if(password!==confirmPassword){showNotification('As senhas não coincidem!','error');return}const result=registerUser(name,email,password);if(result.success){showNotification('Conta criada com sucesso! Faça login.','success');setTimeout(()=>{showLogin();loginEmail.value=email;registerForm.reset();updatePasswordStrength('')},1500)}else showNotification(result.message,'error')});
registerPassword.addEventListener('input',e=>updatePasswordStrength(e.target.value));
function updatePasswordStrength(password){if(!password){registerPasswordStrength.innerHTML='';registerPasswordStrength.className='password-strength';return}let strength=0;if(password.length>=6)strength++;if(password.length>=8)strength++;if(/[a-z]/.test(password))strength++;if(/[A-Z]/.test(password))strength++;if(/[0-9]/.test(password))strength++;if(/[^a-zA-Z0-9]/.test(password))strength++;const strengthClass=strength<=2?'weak':strength<=4?'medium':'strong';registerPasswordStrength.innerHTML='<div class="password-strength-bar"></div>';registerPasswordStrength.className=`password-strength ${strengthClass}`}
togglePasswordButtons.forEach(btn=>{btn.addEventListener('click',()=>{const input=document.getElementById(btn.dataset.target);if(input.type==='password'){input.type='text';btn.textContent='🙈'}else{input.type='password';btn.textContent='👁️'}})});
lengthSlider.addEventListener('input',e=>{lengthValue.textContent=e.target.value;lengthValue.style.transform='scale(1.2)';setTimeout(()=>lengthValue.style.transform='scale(1)',200)});
normalModeBtn.addEventListener('click',()=>switchMode('normal'));
memorableModeBtn.addEventListener('click',()=>switchMode('memorable'));
pinModeBtn.addEventListener('click',()=>switchMode('pin'));
function switchMode(mode){currentMode=mode;normalModeBtn.classList.toggle('active',mode==='normal');memorableModeBtn.classList.toggle('active',mode==='memorable');pinModeBtn.classList.toggle('active',mode==='pin');if(mode==='pin'){lengthSlider.min=4;lengthSlider.max=12;lengthSlider.value=6;lengthValue.textContent='6';uppercaseCheck.checked=false;lowercaseCheck.checked=false;symbolsCheck.checked=false;numbersCheck.checked=true}else if(mode==='memorable'){lengthSlider.min=12;lengthSlider.max=32;lengthSlider.value=20;lengthValue.textContent='20'}else{lengthSlider.min=4;lengthSlider.max=64;lengthSlider.value=16;lengthValue.textContent='16'}}
generateMultipleCheck.addEventListener('change',e=>{multipleCountContainer.style.display=e.target.checked?'flex':'none'});
function generatePassword(){if(!currentUser){showNotification('Faça login para usar o gerador!','warning');return}const length=parseInt(lengthSlider.value);let password='';if(currentMode==='pin')password=generatePIN(length);else if(currentMode==='memorable')password=generateMemorablePassword(length);else password=generateNormalPassword(length);if(generateMultipleCheck.checked)generateMultiplePasswords(parseInt(multipleCountInput.value));else{displayPassword(password);addToHistory(password);updateStats(password);updateAnalysis(password)}generateBtn.style.transform='scale(0.95)';setTimeout(()=>generateBtn.style.transform='scale(1)',150)}
function generateNormalPassword(length){let charset='';if(uppercaseCheck.checked)charset+=uppercase;if(lowercaseCheck.checked)charset+=lowercase;if(numbersCheck.checked)charset+=numbers;if(symbolsCheck.checked)charset+=symbols;if(excludeSimilarCheck.checked)charset=charset.split('').filter(c=>!similarChars.includes(c)).join('');if(charset===''){showNotification('Selecione pelo menos uma opção!','warning');return''}let password='';const array=new Uint32Array(length);crypto.getRandomValues(array);for(let i=0;i<length;i++)password+=charset[array[i]%charset.length];return password}
function generatePIN(length){let pin='';const array=new Uint32Array(length);crypto.getRandomValues(array);for(let i=0;i<length;i++)pin+=numbers[array[i]%numbers.length];return pin}
function generateMemorablePassword(length){const wordCount=Math.floor(length/4),remaining=length%4;let password='';for(let i=0;i<wordCount;i++){const randomIndex=Math.floor(Math.random()*memorableWords.length);let word=memorableWords[randomIndex];word=word.charAt(0).toUpperCase()+word.slice(1);password+=word;if(i<wordCount-1||remaining>0){const randomNum=Math.floor(Math.random()*10);password+=randomNum}}if(remaining>0){const symbols='!@#$%';for(let i=0;i<remaining;i++)password+=symbols[Math.floor(Math.random()*symbols.length)]}return password.substring(0,length)}
function generateMultiplePasswords(count){const passwords=[];for(let i=0;i<count;i++){const length=parseInt(lengthSlider.value);let pwd='';if(currentMode==='pin')pwd=generatePIN(length);else if(currentMode==='memorable')pwd=generateMemorablePassword(length);else pwd=generateNormalPassword(length);passwords.push(pwd);addToHistory(pwd)}displayMultiplePasswords(passwords);showNotification(`${count} senhas geradas!`,'success')}
function displayPassword(password){if(!password)return;passwordOutput.value='';passwordOutput.style.opacity='0.5';setTimeout(()=>{let index=0;const typeInterval=setInterval(()=>{if(index<password.length){passwordOutput.value+=password[index];index++}else{clearInterval(typeInterval);passwordOutput.style.opacity='1';passwordOutput.style.transform='scale(1.02)';setTimeout(()=>passwordOutput.style.transform='scale(1)',200)}},30)},100);updateStrength(password)}
function displayMultiplePasswords(passwords){passwordOutput.value=passwords[0];updateStrength(passwords[0]);updateStats(passwords[0]);updateAnalysis(passwords[0])}
function updateStrength(password){if(!password)return;let strength=0;if(password.length>=8)strength++;if(password.length>=12)strength++;if(password.length>=16)strength++;if(password.length>=20)strength++;if(/[a-z]/.test(password))strength++;if(/[A-Z]/.test(password))strength++;if(/[0-9]/.test(password))strength++;if(/[^a-zA-Z0-9]/.test(password))strength++;if(!/(.)\1{2,}/.test(password))strength++;let strengthLabel='',strengthPercent=0;if(strength<=2){strengthLabel='Muito Fraca';strengthPercent=20;strengthText.style.color='var(--danger)'}else if(strength<=4){strengthLabel='Fraca';strengthPercent=40;strengthText.style.color='var(--danger)'}else if(strength<=6){strengthLabel='Média';strengthPercent=60;strengthText.style.color='var(--warning)'}else if(strength<=8){strengthLabel='Forte';strengthPercent=80;strengthText.style.color='#f59e0b'}else{strengthLabel='Muito Forte';strengthPercent=100;strengthText.style.color='var(--success)'}strengthFill.style.width=strengthPercent+'%';strengthText.textContent=strengthLabel;strengthFill.style.transform='scaleX(0)';setTimeout(()=>strengthFill.style.transform='scaleX(1)',100)}
function calculateEntropy(password){if(!password)return 0;let charsetSize=0;if(/[a-z]/.test(password))charsetSize+=26;if(/[A-Z]/.test(password))charsetSize+=26;if(/[0-9]/.test(password))charsetSize+=10;if(/[^a-zA-Z0-9]/.test(password))charsetSize+=32;return Math.log2(Math.pow(charsetSize,password.length))}
function estimateCrackTime(entropy){const attemptsPerSecond=1e9,totalCombinations=Math.pow(2,entropy),seconds=totalCombinations/attemptsPerSecond;if(seconds<60)return`${seconds.toFixed(0)} segundos`;if(seconds<3600)return`${(seconds/60).toFixed(1)} minutos`;if(seconds<86400)return`${(seconds/3600).toFixed(1)} horas`;if(seconds<31536000)return`${(seconds/86400).toFixed(1)} dias`;if(seconds<31536000000)return`${(seconds/31536000).toFixed(1)} anos`;return`${(seconds/31536000000).toFixed(1)} milênios`}
function formatNumber(num){if(num<1000)return num.toString();if(num<1e6)return(num/1000).toFixed(1)+'K';if(num<1e9)return(num/1e6).toFixed(1)+'M';if(num<1e12)return(num/1e9).toFixed(1)+'B';return(num/1e12).toFixed(1)+'T'}
function updateStats(password){if(!password){entropyValue.textContent='-';crackTime.textContent='-';combinations.textContent='-';return}const entropy=calculateEntropy(password),time=estimateCrackTime(entropy),comb=Math.pow(2,entropy);entropyValue.textContent=entropy.toFixed(1)+' bits';crackTime.textContent=time;combinations.textContent=formatNumber(comb)}
function updateAnalysis(password){if(!password){analysisContent.innerHTML='<p class="empty-message">Gere uma senha para ver a análise</p>';return}const analysis=[];analysis.push(`<div class="analysis-item"><strong>Comprimento:</strong> ${password.length} caracteres ${password.length>=12?'✓':'⚠ Recomendado: 12+'}</div>`);const hasLower=/[a-z]/.test(password),hasUpper=/[A-Z]/.test(password),hasNumbers=/[0-9]/.test(password),hasSymbols=/[^a-zA-Z0-9]/.test(password);analysis.push(`<div class="analysis-item"><strong>Tipos de caracteres:</strong> ${hasLower?'✓':'✗'} Minúsculas, ${hasUpper?'✓':'✗'} Maiúsculas, ${hasNumbers?'✓':'✗'} Números, ${hasSymbols?'✓':'✗'} Símbolos</div>`);const commonPatterns=[];if(/(.)\1{2,}/.test(password))commonPatterns.push('Repetições');if(/123|abc|qwe/i.test(password))commonPatterns.push('Sequências');if(/password|admin|123456/i.test(password))commonPatterns.push('Palavras comuns');if(commonPatterns.length>0)analysis.push(`<div class="analysis-item"><strong>⚠ Padrões detectados:</strong> ${commonPatterns.join(', ')}</div>`);else analysis.push(`<div class="analysis-item"><strong>✓ Padrões:</strong> Nenhum padrão comum detectado</div>`);const entropy=calculateEntropy(password);let entropyLevel='';if(entropy<40)entropyLevel='Baixa';else if(entropy<60)entropyLevel='Média';else if(entropy<80)entropyLevel='Alta';else entropyLevel='Muito Alta';analysis.push(`<div class="analysis-item"><strong>Entropia:</strong> ${entropy.toFixed(1)} bits (${entropyLevel})</div>`);const suggestions=[];if(password.length<12)suggestions.push('Aumente o comprimento');if(!hasLower)suggestions.push('Adicione letras minúsculas');if(!hasUpper)suggestions.push('Adicione letras maiúsculas');if(!hasNumbers)suggestions.push('Adicione números');if(!hasSymbols)suggestions.push('Adicione símbolos');if(suggestions.length>0)analysis.push(`<div class="analysis-item"><strong>💡 Sugestões:</strong> ${suggestions.join(', ')}</div>`);analysisContent.innerHTML=analysis.join('')}
function addToHistory(password){if(!password||!currentUser)return;const historyItem={password,timestamp:new Date().toISOString(),strength:calculateStrengthLevel(password),entropy:calculateEntropy(password)};passwordHistory.unshift(historyItem);if(passwordHistory.length>50)passwordHistory=passwordHistory.slice(0,50);savePasswordHistory(passwordHistory);updateHistoryDisplay()}
function calculateStrengthLevel(password){let strength=0;if(password.length>=8)strength++;if(password.length>=12)strength++;if(password.length>=16)strength++;if(/[a-z]/.test(password))strength++;if(/[A-Z]/.test(password))strength++;if(/[0-9]/.test(password))strength++;if(/[^a-zA-Z0-9]/.test(password))strength++;if(strength<=2)return'Fraca';if(strength<=4)return'Média';if(strength<=6)return'Forte';return'Muito Forte'}
function updateHistoryDisplay(){if(passwordHistory.length===0){historyList.innerHTML='<p class="empty-message">Nenhuma senha gerada ainda</p>';return}historyList.innerHTML=passwordHistory.map((item,index)=>{const date=new Date(item.timestamp),timeStr=date.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});return`<div class="history-item"><span class="history-password" title="${item.password}">${item.password}</span><div class="history-actions"><button class="history-btn" onclick="copyFromHistory('${item.password}')">📋</button><button class="history-btn" onclick="removeFromHistory(${index})">🗑️</button></div></div>`}).join('')}
function copyFromHistory(password){navigator.clipboard.writeText(password).then(()=>showNotification('Senha copiada!','success'))}
function removeFromHistory(index){passwordHistory.splice(index,1);savePasswordHistory(passwordHistory);updateHistoryDisplay()}
clearHistoryBtn.addEventListener('click',()=>{if(confirm('Tem certeza que deseja limpar o histórico?')){passwordHistory=[];savePasswordHistory(passwordHistory);updateHistoryDisplay();showNotification('Histórico limpo!','success')}});
tabButtons.forEach(btn=>{btn.addEventListener('click',()=>{const tabName=btn.dataset.tab;tabButtons.forEach(b=>b.classList.remove('active'));tabContents.forEach(c=>c.classList.remove('active'));btn.classList.add('active');document.getElementById(tabName+'Tab').classList.add('active')})});
exportTxtBtn.addEventListener('click',()=>{if(!currentUser){showNotification('Faça login para exportar!','warning');return}if(passwordHistory.length===0){showNotification('Nenhuma senha no histórico!','warning');return}const content=passwordHistory.map(item=>`${item.password} | ${new Date(item.timestamp).toLocaleString('pt-BR')} | ${item.strength}`).join('\n');downloadFile(`senhas_${currentUser.email}.txt`,content,'text/plain');showNotification('Arquivo TXT exportado!','success')});
exportJsonBtn.addEventListener('click',()=>{if(!currentUser){showNotification('Faça login para exportar!','warning');return}if(passwordHistory.length===0){showNotification('Nenhuma senha no histórico!','warning');return}downloadFile(`senhas_${currentUser.email}.json`,JSON.stringify(passwordHistory,null,2),'application/json');showNotification('Arquivo JSON exportado!','success')});
exportCsvBtn.addEventListener('click',()=>{if(!currentUser){showNotification('Faça login para exportar!','warning');return}if(passwordHistory.length===0){showNotification('Nenhuma senha no histórico!','warning');return}const headers='Senha,Data,Força,Entropia\n';const rows=passwordHistory.map(item=>`"${item.password}","${new Date(item.timestamp).toLocaleString('pt-BR')}","${item.strength}","${item.entropy.toFixed(1)}"`).join('\n');downloadFile(`senhas_${currentUser.email}.csv`,headers+rows,'text/csv');showNotification('Arquivo CSV exportado!','success')});
function downloadFile(filename,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
importBtn.addEventListener('click',()=>importFileInput.click());
importFileInput.addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=event=>{try{const content=event.target.result;let imported=[];if(file.name.endsWith('.json'))imported=JSON.parse(content);else if(file.name.endsWith('.csv')){const lines=content.split('\n').slice(1);imported=lines.filter(l=>l.trim()).map(line=>{const[password,timestamp,strength,entropy]=line.split(',');return{password:password.replace(/"/g,''),timestamp:timestamp.replace(/"/g,''),strength:strength.replace(/"/g,''),entropy:parseFloat(entropy.replace(/"/g,''))}})}else{const lines=content.split('\n');imported=lines.filter(l=>l.trim()).map(line=>{const parts=line.split(' | ');return{password:parts[0],timestamp:new Date().toISOString(),strength:parts[2]||'Média',entropy:0}})}passwordHistory=[...imported,...passwordHistory].slice(0,50);savePasswordHistory(passwordHistory);updateHistoryDisplay();showNotification(`${imported.length} senhas importadas!`,'success')}catch(error){showNotification('Erro ao importar arquivo!','error')}};reader.readAsText(file)});
function copyPassword(){if(passwordOutput.value&&passwordOutput.value!=='Clique em Gerar Senha'){navigator.clipboard.writeText(passwordOutput.value).then(()=>{showNotification('Senha copiada! 📋','success');copyBtn.style.transform='translateY(-50%) scale(1.2) rotate(360deg)';setTimeout(()=>copyBtn.style.transform='translateY(-50%) scale(1) rotate(0deg)',300)}).catch(()=>showNotification('Erro ao copiar!','error'))}else showNotification('Gere uma senha primeiro!','warning')}
function showNotification(message,type='success'){notification.textContent=message;notification.className='notification show';if(type==='success')notification.style.background='var(--success)';else if(type==='warning')notification.style.background='var(--warning)';else notification.style.background='var(--danger)';setTimeout(()=>notification.classList.remove('show'),3000)}
generateBtn.addEventListener('click',generatePassword);
refreshBtn.addEventListener('click',generatePassword);
copyBtn.addEventListener('click',copyPassword);
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.target.matches('input[type="number"]'))generatePassword()});
function checkOptions(){const hasOption=uppercaseCheck.checked||lowercaseCheck.checked||numbersCheck.checked||symbolsCheck.checked||currentMode==='pin'||currentMode==='memorable';generateBtn.disabled=!hasOption;generateBtn.style.opacity=hasOption?'1':'0.5'}
uppercaseCheck.addEventListener('change',checkOptions);
lowercaseCheck.addEventListener('change',checkOptions);
numbersCheck.addEventListener('change',checkOptions);
symbolsCheck.addEventListener('change',checkOptions);
checkAuth();
checkOptions();
if(currentUser)loadUserHistory();
function createParticle(){const particle=document.createElement('div');particle.style.position='fixed';particle.style.width='4px';particle.style.height='4px';particle.style.background='rgba(99, 102, 241, 0.6)';particle.style.borderRadius='50%';particle.style.pointerEvents='none';particle.style.zIndex='0';particle.style.left=Math.random()*100+'%';particle.style.top='100%';particle.style.boxShadow='0 0 10px rgba(99, 102, 241, 0.8)';document.body.appendChild(particle);const duration=3+Math.random()*2,delay=Math.random()*2;particle.style.animation=`floatUp ${duration}s ${delay}s ease-out forwards`;setTimeout(()=>particle.remove(),(duration+delay)*1000)}
const style=document.createElement('style');style.textContent=`@keyframes floatUp{to{transform:translateY(-100vh) translateX(${Math.random()*200-100}px);opacity:0}}`;document.head.appendChild(style);
setInterval(createParticle,2000);
